### PR TITLE
fix(client-adapters): arethusaAdapter map person values

### LINKED ISSUE #226: arethusaAdapter map person property values
For Greek, Arethusa may report the following values for person

'first person'
'second person'
'third person'

these need to be mapped to the standard values

'1st'
'2nd'
'3rd'

### PR DESCRIPTION
**Pull request by balmas**
arethusaAdapter map person values

fix #226

### CODE REVIEW

File: packages/client-adapters/src/adapters/arethusa/adapter.js [hunk 1]
```diff
@@ -99,7 +99,17 @@ class ArethusaTreebankAdapter extends BaseAdapter {
           this.addError(this.l10n.messages['MORPH_TREEBANK_UNSUPPORTED_LANGUAGE'].get(languageID))
           return
         }
-        const transformAdapter = new AlpheiosLexiconTransformer(this, new ImportData(languageModel, 'arethusa'))
+        let mapper = new ImportData(languageModel,'arethusa')
+        mapper.setPropertyParser(function (propertyName, propertyValue, inputElem) {
+          let propertyValues = []
```
Comment (kirlat) [inline packages/client-adapters/src/adapters/arethusa/adapter.js:104]: Are we using `propertyValues` anywhere?

Comment (balmas) [reply packages/client-adapters/src/adapters/arethusa/adapter.js:104]: oh thanks for catching that, was from a prior iteration. Will fix before merge.
